#%RAML 1.0
title: projet
version: v1
baseUri: /

/creation-devis:
  post:
    body:
      application/json:
        properties:
            id: string
            experience: array
            date_start: datetime
            date_end: datetime
            food: object
            transport: object
            
/reservation:
  /users:
    get:
      responses:
          200:
            body:
              application/json:
                properties:
                  _id: string
                  userId: string
                  name: string
  post:
    body:
      application/json:
        properties:
            devis: object
            userId: string
            payement: number
        
 
